# Generated by Django 6.0.6 on 2026-07-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='brand',
        ),
    ]
